application: haveabitof
version: 1
runtime: python
api_version: 1

default_expiration: "3650d"

handlers:
- url: /
  script: app.py

- url: /about
  script: app.py

- url: /api
  script: app.py

- url: /apihelp
  script: app.py

- url: /reveal
  script: app.py

- url: /cron/gc
  script: cron/gc.py
  login: admin

- url: /style
  static_dir: style

- url: /favicon.ico
  static_files: media/favicon.ico
  upload: media/favicon.ico

- url: /robots.txt
  static_files: media/robots.txt
  upload: media/robots.txt