application: haveabitof
version: 1
runtime: python
api_version: 1

default_expiration: "3650d"

handlers:
- url: /
  script: app.py

- url: /about
  script: app.py

- url: /api
  script: app.py

- url: /apihelp
  script: app.py

- url: /style
  static_dir: style

- url: /favicon.ico
  static_files: media/2011-02-04-favicon.ico
  upload: media/2011-02-04-favicon.ico

- url: /robots.txt
  static_files: media/2011-02-04-robots.txt
  upload: media/2011-02-04-robots.txt

- url: /admin(/.*)?
  script: admin.py
  login: admin

- url: /console/static
  static_dir: app-engine-console/console/console/app/view/static
  expiration: 30m
  login: admin

- url: /console.*
  script: app-engine-console/console/console/app/console.py
  login: admin

- url: /.*
  script: app.py
